### ISSUE TITLE
BRAINStools NOT compiling if BRAINSDEMONWARP_DEBUG_OUTPUT OFF + ITK_VERSION_MAJOR:3

### ISSUE THREAD

**Issue by jcfr** [BRAINSia/BRAINSStandAlone#13]
Please see comment associated with the following commit: https://github.com/BRAINSia/BRAINSStandAlone/commit/8778dc548e26205d003ffd151869f8236062d367

**Comment by hjmjohnson** [comment]
fixed #13 in 3733b589995605ed4fc00e7956ff44cc78f2cc5e

**Comment by hjmjohnson** [comment]
fixed #13 in 3733b58
