### ISSUE TITLE
GTRACTCommonLib is missing install rules

### ISSUE THREAD

**Issue by jcfr** [BRAINSia/BRAINSStandAlone#14]
This is causing issue in packages like Slicer where the library is expected to be packaged. 

See https://github.com/BRAINSia/BRAINSStandAlone/blob/master/GTRACT/Common/CMakeLists.txt

**Comment by hjmjohnson** [comment]
fixed #14:

avoid needed to install by building static 

Committed in 917c7f41d9cd06d47e58d0107286dd4dd0528385
