### ISSUE TITLE
Add option BRAINSTools_INSTALL_DEVELOPMENT

### ISSUE THREAD

**Issue by jcfr** [BRAINSia/BRAINSStandAlone#15]
When packaged within Slicer, there are extra folders named ''include'' and ''lib'' at the root of the bundle. These ones corresponds to the development headers/files of BRAINSTools. 

To avoid these extra files from being installed. An option named BRAINSTools_INSTALL_DEVELOPMENT could be added.

Aware these files are already associated with the Development component, this option can provide an easy way to enable/disable their installation without having to specify the explicit list of components that should be installed within Slicer. See https://github.com/Slicer/Slicer/blob/master/SlicerCPack.cmake#L60

A similar approach is followed within VTK and CTK

**Comment by hjmjohnson** [comment]
JC,

I don't understand what would need to be done here.  Sorry, but I don't see how line 60 of https://github.com/Slicer/Slicer/blob/master/SlicerCPack.cmake#L60 helps describe what I would need to do.

Hans

**Comment by jcfr** [comment]
line 60 of https://github.com/Slicer/Slicer/blob/master/SlicerCPack.cmake#L60  illustrates the fact we install all component in Slicer. BRAINStools being included in Slicer itself, it applies to BRAINSTools also. That's why having an option like BRAINSTools_INSTALL_DEVELOPMENT would be nice.

**Comment by jcfr** [comment]
Would it be possible to re-open the issue ? 

Seems that install rules specific to headers component are not excluded if the option is disabled.
As an example, see https://github.com/BRAINSia/BRAINSStandAlone/blob/master/BRAINSCommonLib/CMakeLists.txt#L36

**Comment by hjmjohnson** [comment]
It can be re-opened, but I have no idea how to resolve this problem.

I see what you have highlighted, but I don't know what to do about it.
