### ISSUE TITLE
Branch SlicerITKv3Patches is missing

### ISSUE THREAD

**Issue by jcfr** [BRAINSia/BRAINSStandAlone#76]
This morning Slicer dashboards started to fail with the following message:

```
fatal: reference is not a tree: 03ce71cca9bbfb1f0da0040b139011211694b1c6
CMake Error at BRAINSTools-prefix/tmp/BRAINSTools-gitclone.cmake:28 (message):
  Failed to checkout tag: '03ce71cca9bbfb1f0da0040b139011211694b1c6'
```

See http://slicer.cdash.org/viewBuildError.php?buildid=20596

The error is reproducible doing the following:

```
$ git clone git://github.com/BRAINSia/BRAINSStandAlone.git BRAINSTools
$ cd BRAINSTools
$ git checkout 03ce71cca9bbfb1f0da0040b139011211694b1c6
fatal: reference is not a tree: 03ce71cca9bbfb1f0da0040b139011211694b1c6
```

The branch `SlicerITKv3Patches` has been deleted from BRAINSSia/BRAINSStandAlone repository, would be great if it could be restored. 

![BRAINS_Slicer_ITKv3_Patches_missing](http://s16.postimage.org/k0d6ora4l/BRAINS_Slicer_ITKv3_Patches_missing.png)

**Comment by hjmjohnson** [comment]
Sorry,

I did some house cleaning yesterday.  I forgot that this branch was in use
by Slicer with ITKv3.

It should now be restored.

Hans

-----Original Message-----
From: Jean-Christophe Fillion-Robin
<reply+i-4718654-ddf5d931e76fb86177a73b7738b5f1296c087d2b-313970@reply.gith
ub.com>
Date: Wednesday, May 23, 2012 2:12 PM
To: Hans Johnson hans.j.johnson@gmail.com
Subject: [BRAINSStandAlone] Branch SlicerITKv3Patches is missing (#76)

This morning Slicer dashboards started to fail with the following message:

```
fatal: reference is not a tree: 03ce71cca9bbfb1f0da0040b139011211694b1c6
CMake Error at BRAINSTools-prefix/tmp/BRAINSTools-gitclone.cmake:28
(message):
  Failed to checkout tag: '03ce71cca9bbfb1f0da0040b139011211694b1c6'
```

See http://slicer.cdash.org/viewBuildError.php?buildid=20596

The error is reproducible doing the following:

```
$ git clone git://github.com/BRAINSia/BRAINSStandAlone.git BRAINSTools
$ cd BRAINSTools
$ git checkout 03ce71cca9bbfb1f0da0040b139011211694b1c6
fatal: reference is not a tree: 03ce71cca9bbfb1f0da0040b139011211694b1c6
```

The branch `SlicerITKv3Patches` has been deleted from
BRAINSSia/BRAINSStandAlone repository, would be great if it could be
restored. 

![BRAINS_Slicer_ITKv3_Patches_missing](http://s16.postimage.org/k0d6ora4l/B
RAINS_Slicer_ITKv3_Patches_missing.png)

---

Reply to this email directly or view it on GitHub:
https://github.com/BRAINSia/BRAINSStandAlone/issues/76

**Comment by jcfr** [comment]
Thanks Hans :)
Jc

On Wed, May 23, 2012 at 3:17 PM, hjmjohnson <
reply@reply.github.com

> wrote:
> 
> Sorry,
> 
> I did some house cleaning yesterday.  I forgot that this branch was in use
> by Slicer with ITKv3.
> 
> It should now be restored.
> 
> Hans
> 
> -----Original Message-----
> From: Jean-Christophe Fillion-Robin
> <reply+i-4718654-ddf5d931e76fb86177a73b7738b5f1296c087d2b-313970@reply.gith
> ub.com>
> Date: Wednesday, May 23, 2012 2:12 PM
> To: Hans Johnson hans.j.johnson@gmail.com
> Subject: [BRAINSStandAlone] Branch SlicerITKv3Patches is missing (#76)
> 
> This morning Slicer dashboards started to fail with the following message:
> 
> ```
> fatal: reference is not a tree: 03ce71cca9bbfb1f0da0040b139011211694b1c6
> CMake Error at BRAINSTools-prefix/tmp/BRAINSTools-gitclone.cmake:28
> (message):
>  Failed to checkout tag: '03ce71cca9bbfb1f0da0040b139011211694b1c6'
> ```
> 
> See http://slicer.cdash.org/viewBuildError.php?buildid=20596
> 
> The error is reproducible doing the following:
> 
> ```
> $ git clone git://github.com/BRAINSia/BRAINSStandAlone.git BRAINSTools
> $ cd BRAINSTools
> $ git checkout 03ce71cca9bbfb1f0da0040b139011211694b1c6
> fatal: reference is not a tree: 03ce71cca9bbfb1f0da0040b139011211694b1c6
> ```
> 
> The branch `SlicerITKv3Patches` has been deleted from
> BRAINSSia/BRAINSStandAlone repository, would be great if it could be
> restored.
> 
> ![BRAINS_Slicer_ITKv3_Patches_missing](http://s16.postimage.org/k0d6ora4l/B
> RAINS_Slicer_ITKv3_Patches_missing.png)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/BRAINSia/BRAINSStandAlone/issues/76
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/BRAINSia/BRAINSStandAlone/issues/76#issuecomment-5882001

## 

+1 919 869 8849
